services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:management
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    env_file: .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    build: .
    image: r162809ws/myshop-web:${TAG:-latest}
    command: ["./wait-for-it.sh", "db:5432", "--", "sh", "-c", "python myshop/manage.py migrate --settings=myshop.settings.prod && python myshop/manage.py collectstatic --noinput --settings=myshop.settings.prod && if [ \"$(python myshop/manage.py shell --settings=myshop.settings.prod -c 'from django.contrib.auth import get_user_model; User = get_user_model(); print(User.objects.filter(is_superuser=True).exists())')\" != 'True' ]; then python myshop/manage.py createsuperuser --noinput --settings=myshop.settings.prod; fi && uwsgi --ini /app/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/app
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  celery:
    build: .
    command: celery -A myshop worker -l info --hostname=celery@%h
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - PYTHONPATH=/app/myshop
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/app
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      web:
        condition: service_started
      flower:
        condition: service_started
    secrets:
      - myshop.crt
      - myshop.key
  flower:
    build: .
    env_file: .env
    command: celery -A myshop flower --url-prefix=/flower --hostname=flower@%h
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - PYTHONPATH=/app/myshop
    depends_on:
      celery:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/flower/"]
      interval: 30s
      timeout: 10s
      retries: 5

secrets:
  myshop.crt:
    file: ./ssl/myshop.crt  # Путь к cert на хосте (в папке cozy)
  myshop.key:
    file: ./ssl/myshop.key  # Путь к key на хосте