services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
  rabbitmq:
    image: rabbitmq:management
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    env_file: .env
  web:
    build: .
    image: r162809ws/myshop-web:${TAG:-latest}
    command: ["./wait-for-it.sh", "db:5432", "--", "sh", "-c", "python myshop/manage.py migrate && python myshop/manage.py collectstatic --noinput && uwsgi --ini /app/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/app
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
    depends_on:
      - db
      - rabbitmq
  celery:
    image: r162809ws/myshop-web:latest
    command: celery -A myshop worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - PYTHONPATH=/app
    volumes:
      - ./myshop:/app
    env_file: .env
    depends_on:
      - db
      - web
      - rabbitmq
  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/app
      
    ports:
      - "80:80"
      - "443:443"

