# Generated by Django 5.2.8 on 2025-12-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("referrer", models.URLField(blank=True, null=True)),
                ("visit_time", models.DateTimeField(auto_now_add=True)),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("views_count", models.PositiveIntegerField(default=1)),
                ("last_visit", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Визит пользователя",
                "verbose_name_plural": "Визиты пользователей",
            },
        ),
    ]
