# Generated by Django 5.1.4 on 2025-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
