# Generated by Django 5.1.4 on 2025-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_user', '0002_visit_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='page_views',
            field=models.IntegerField(default=1),
        ),
    ]
