# Generated by Django 5.1.4 on 2025-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_user', '0003_alter_visit_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='device_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
