# Generated by Django 5.1.4 on 2025-03-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_user', '0003_visit_page_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='page_views',
        ),
    ]
