# Generated by Django 5.1.4 on 2025-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_user', '0004_remove_visit_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='views_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
