# Generated by Django 5.1.4 on 2025-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_user', '0004_alter_visit_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
