# Generated by Django 5.1.4 on 2025-03-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_user', '0005_visit_last_visit_visit_views_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Визит пользователя', 'verbose_name_plural': 'Визиты пользователей'},
        ),
    ]
