# Generated by Django 5.2.8 on 2026-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_picker",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, пользователь видит все заказы со статусом 'В обработке'.",
                verbose_name="Посредник",
            ),
        ),
    ]
