# Generated by Django 5.1.4 on 2025-10-31 00:16

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.User.user_directory_path, verbose_name='Фотография'),
        ),
    ]
