# Generated by Django 5.2.8 on 2026-01-11 08:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_assigned_to_and_more"),
        ("users", "0002_user_is_picker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="delivery_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.deliverymethod",
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон должен быть в формате: +7 (XXX) XXX-XX-XX, 8 (XXX) XXX-XX-XX, +7XXXXXXXXXX или 8XXXXXXXXXX, где X - цифры.",
                        regex="^(?:\\+7|8)\\s*\\(?\\d{3}\\)?\\s*\\d{3}-\\d{2}-\\d{2}$|^(?:\\+7|8)\\d{10}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Индекс должен состоять только из 6 цифр.",
                        regex="^\\d{6}$",
                    )
                ],
                verbose_name="Почтовый индекс",
            ),
        ),
    ]
