# Generated by Django 5.2.8 on 2026-01-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_delivery_method_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Регион"
            ),
        ),
    ]
