# Generated by Django 5.1.4 on 2025-03-06 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Телефон должен начинаться с +7 и содержать 12 цифр.', regex='^\\+7\\d{12}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Индекс должен состоять только из цифр.', regex='^\\d+$')], verbose_name='Почтовый индекс'),
        ),
    ]
