# Generated by Django 5.1.4 on 2025-03-06 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_alter_user_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Телефон должен начинаться с +7 и содержать 12 цифр.', regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
