# Generated by Django 5.1.4 on 2025-03-06 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Телефон должен начинаться с +7 или 8 и содержать 10 цифр.', regex='^(?:\\+7|8)\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
