# Generated by Django 5.1.4 on 2025-03-15 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Индекс должен состоять только из 6 цифр.', regex='^\\d{6}$')], verbose_name='Почтовый индекс'),
        ),
    ]
