# Generated by Django 5.1.4 on 2025-03-05 21:55

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Способ доставки')),
                ('price_delivery', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена доставки')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('amount', 'Скидка в рублях'), ('percentage', 'Скидка в %')], max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Размер скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_last_name', models.CharField(max_length=255, verbose_name='Фамилия Имя Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Телефон должен содержать только цифры и быть длиной от 10 до 12 символов.', regex='^\\d{10,12}$')], verbose_name='Телефон')),
                ('region', models.CharField(max_length=250, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Индекс должен состоять только из цифр.', regex='^\\d+$')], verbose_name='Индекс')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Паспортные данные должны состоять из 10 цифр.', regex='^\\d{10}$')], verbose_name='Паспортные данные')),
                ('comment', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Товар Оплачен')),
                ('zamena_product', models.BooleanField(default=True, verbose_name='Предлагать замену товара')),
                ('strahovat_gruz', models.BooleanField(default=True, verbose_name='Застраховать груз')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('obrabotka', 'В обработке'), ('oplata', 'Ожидает оплаты'), ('assembled', 'Собран'), ('canceled', 'Отменен'), ('pending', 'В ожидании')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('delivery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverymethod', verbose_name='Способ доставки')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.discount', verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.product', verbose_name='Название товара')),
            ],
            options={
                'verbose_name': 'Заказанный товар',
                'verbose_name_plural': 'Заказанные товары',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='orders_orde_created_743fca_idx'),
        ),
    ]
