# Generated by Django 5.2.8 on 2026-01-06 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Индекс должен состоять только из 6 цифр.",
                        regex="^\\d{6}$",
                    )
                ],
                verbose_name="Почтовый индекс",
            ),
        ),
    ]
