# Generated by Django 5.2.8 on 2025-11-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Цена продажи",
            ),
        ),
    ]
