# Generated by Django 5.1.4 on 2025-04-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_article_number_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product', 'size')},
        ),
    ]
