# Generated by Django 5.1.4 on 2025-02-18 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymethod',
            old_name='name',
            new_name='title',
        ),
    ]
