# Generated by Django 5.2.8 on 2025-11-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_productprice_is_hidden"),
        ("orders", "0002_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="home.productprice",
                verbose_name="Вариация товара",
            ),
        ),
    ]
