# Generated by Django 5.1.4 on 2025-02-18 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_name_deliverymethod_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.deliverymethod', verbose_name='Способ доставки'),
        ),
    ]
