# Generated by Django 5.2.8 on 2026-01-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_picked",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Позиция собрана (склад)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="picked_comment",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Комментарий склада",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="picked_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Фактическое количество (склад)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="picked_zacup_price",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Фактическая цена (склад)",
            ),
        ),
    ]
