# Generated by Django 5.1.4 on 2025-02-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.deliverymethod', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='passport_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Паспортные данные'),
        ),
    ]
