# Generated by Django 5.1.4 on 2025-03-06 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Паспортные данные должны состоять из 10 цифр.', regex='^\\d{10}$')], verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Телефон должен начинаться с +7 и содержать 12 цифр.', regex='^\\+7\\d{12}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Индекс должен состоять только из цифр.', regex='^\\d+$')], verbose_name='Почтовый индекс'),
        ),
    ]
