# Generated by Django 5.2.8 on 2025-11-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_productprice_size"),
        ("orders", "0003_alter_orderitem_product_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="article_snapshot",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Артикул (архив)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="mesto_snapshot",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Место (архив)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_snapshot",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Товар (архив)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_snapshot",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Размер (архив)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="zacup_price_snapshot",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Закупочная цена (архив)",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product_snapshot"], name="orders_orde_product_eca4a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["size_snapshot"], name="orders_orde_size_sn_b474c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["article_snapshot"], name="orders_orde_article_91fbb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["mesto_snapshot"], name="orders_orde_mesto_s_51c763_idx"
            ),
        ),
    ]
