# Generated by Django 5.1.4 on 2025-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='passport_numder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='order',
            name='strahovat_gruz',
            field=models.BooleanField(default=True, verbose_name='Застраховать груз'),
        ),
        migrations.AddField(
            model_name='order',
            name='zamena_product',
            field=models.BooleanField(default=True, verbose_name='Предлагать замену товара'),
        ),
    ]
