# Generated by Django 5.2.8 on 2025-11-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_productprice_size"),
        ("orders", "0004_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Заказанный товар",
                "verbose_name_plural": "Заказанные товары",
            },
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product_price")},
        ),
    ]
