# Generated by Django 5.2.8 on 2026-01-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Заказанный товар",
                "verbose_name_plural": "Заказанные товары",
            },
        ),
    ]
