# Generated by Django 5.1.4 on 2025-02-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliverymethod_order_passport_numder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='passport_numder',
            new_name='passport_number',
        ),
    ]
