# Generated by Django 5.1.4 on 2025-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='price_delivery',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена доставки'),
        ),
    ]
