# Generated by Django 5.2.8 on 2025-11-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_productprice_size"),
        ("orders", "0005_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="home.productprice",
                verbose_name="«Редактировать» или «Изменить» товар",
            ),
        ),
    ]
