# Generated by Django 5.1.4 on 2025-03-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_deliverymethod_price_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('obrabotka', 'В обработке'), ('oplata', 'Ожидает оплаты'), ('assembled', 'Собран'), ('canceled', 'Отменен'), ('pending', 'В ожидании')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
