# Generated by Django 5.1.4 on 2025-02-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_deliverymethod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'verbose_name': 'Способ доставки', 'verbose_name_plural': 'Способы доставки'},
        ),
    ]
