# Generated by Django 5.1.4 on 2025-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_deliverymethod_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспортные данные'),
        ),
    ]
