# Generated by Django 5.1.4 on 2025-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='soglasie_na_obrabotku_danyh',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку перслнальных данных'),
        ),
        migrations.AddField(
            model_name='order',
            name='soglasie_na_uslovie_sotrudnichestva',
            field=models.BooleanField(default=True, verbose_name='Согласие с условиями сотрудничества'),
        ),
    ]
