# Generated by Django 5.1.4 on 2025-03-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_soglasie_na_obrabotku_danyh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='soglasie_na_obrabotku_danyh',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
