# Generated by Django 5.1.4 on 2025-03-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_soglasie_na_obrabotku_danyh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка для клиента', 'verbose_name_plural': 'Скидки для клиентов'},
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='price_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='price_delivery',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена доставки'),
        ),
    ]
