# Generated by Django 5.1.4 on 2025-03-21 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_productprice_home_produc_size_id_bcc1b2_idx'),
        ('orders', '0017_order_my_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.size', verbose_name='Размер'),
        ),
    ]
