# Generated by Django 5.1.4 on 2025-03-26 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_comment_alter_order_my_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'Скидка в рублях'), ('percentage', 'Скидка в %')], db_index=True, max_length=20, verbose_name='Тип скидки'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=20, verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name_last_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Фамилия Имя Отчество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Товар Оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7 (XXX) XXX-XX-XX, 8 (XXX) XXX-XX-XX, +7XXXXXX или 8XXXXXXXXXX, где X - цифры.', regex='^(?:\\+7|8)\\s*\\(?\\d{3}\\)?\\s*\\d{3}-\\d{2}-\\d{2}$|^(?:\\+7|8)\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_delivery',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('obrabotka', 'В обработке'), ('oplata', 'Ожидает оплаты'), ('assembled', 'Собран'), ('canceled', 'Отменен'), ('pending', 'В ожидании')], db_index=True, default='new', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Количество'),
        ),
    ]
