# Generated by Django 5.1.4 on 2025-02-21 18:15

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d', verbose_name='Фото')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.category', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('article_number', models.IntegerField(unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена продажи')),
                ('zacup_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена закупки')),
                ('old_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена старая')),
                ('stock', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('unit', models.CharField(default='шт', max_length=10, verbose_name='Единица измерения')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть товар')),
                ('mesto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Место')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='home.category', verbose_name='Категория')),
                ('size', models.ManyToManyField(blank=True, related_name='size', to='home.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='home_catego_name_a646c2_idx'),
        ),
    ]
