# Generated by Django 5.1.4 on 2025-03-30 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.review'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='home.size', verbose_name='Размер'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='home_catego_name_a646c2_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product'], name='home_produc_product_c7479f_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['size'], name='home_produc_size_id_bcc1b2_idx'),
        ),
    ]
