# Generated by Django 5.1.4 on 2025-02-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zacup_price',
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Размеры'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена продажи')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Старая цена')),
                ('zacup_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена закупки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='home.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='home.size')),
            ],
            options={
                'verbose_name': 'Цена продажи',
                'verbose_name_plural': 'Цена продаж',
            },
        ),
    ]
