# Generated by Django 5.1.4 on 2025-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Размеры'),
        ),
    ]
