# Generated by Django 5.1.4 on 2025-02-08 22:53

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('article_number', models.IntegerField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zacup_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='шт', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='home.category')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siz', to='home.size')),
            ],
        ),
    ]
