# Generated by Django 5.1.4 on 2025-02-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mesto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Место'),
        ),
    ]
