# Generated by Django 5.1.4 on 2025-02-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_productimage_options_remove_product_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='home.size'),
        ),
    ]
