# Generated by Django 5.1.4 on 2025-02-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_size_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.IntegerField(unique=True),
        ),
    ]
