# Generated by Django 5.2.8 on 2025-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productprice",
            options={
                "verbose_name": "Товар, Размер и Цена товара",
                "verbose_name_plural": "Размеры и Цены товара",
            },
        ),
        migrations.AddField(
            model_name="productprice",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Скрыт"
            ),
        ),
    ]
