# Generated by Django 5.1.4 on 2025-03-31 19:41

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, db_index=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Скрыть товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mesto',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(db_index=True, default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(db_index=True, default='шт', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='old_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена старая '),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='zacup_price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=10, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='kachestvo_rating',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Качество товара'),
        ),
        migrations.AlterField(
            model_name='review',
            name='obsluga_rating',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Качество обслуживания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sroki_rating',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Соблюдение сроков'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='review_home/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Размеры'),
        ),
    ]
