# Generated by Django 5.2.8 on 2026-01-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="mesto",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Место",
            ),
        ),
    ]
