# Generated by Django 5.2.8 on 2025-11-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_productprice_options_productprice_is_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productprice",
            name="is_hidden",
        ),
    ]
