# Generated by Django 5.1.4 on 2025-02-23 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_productprice_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Размер и Цена товара', 'verbose_name_plural': 'Размеры и Цены товара'},
        ),
        migrations.AlterField(
            model_name='productprice',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена старая '),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='home.size', verbose_name='Размер'),
        ),
    ]
