# Generated by Django 5.1.4 on 2025-02-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть товар'),
        ),
    ]
