# Generated by Django 5.1.4 on 2025-03-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_review_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
