# Generated by Django 5.2.8 on 2025-11-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_productprice_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_size",
                to="home.size",
                verbose_name="Размер",
            ),
        ),
    ]
