# Generated by Django 5.1.4 on 2025-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Размерная таблица')),
                ('image', models.ImageField(blank=True, null=True, upload_to='size_table/%Y/%m/%d', verbose_name='Изображение')),
            ],
        ),
    ]
