# Generated by Django 5.1.4 on 2025-10-30 14:02

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=home.models.product_image_upload_path, verbose_name='Изображение'),
        ),
    ]
