# Generated by Django 5.1.4 on 2025-03-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_review_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
