# Generated by Django 5.1.4 on 2025-02-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sizetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizetable',
            options={'verbose_name': 'Размерная таблица', 'verbose_name_plural': 'Размерные таблицы'},
        ),
    ]
