# Generated by Django 5.1.4 on 2025-02-09 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_product_size_alter_size_title_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.IntegerField(unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрытый товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена старая'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='zacup_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=10, unique=True, verbose_name='Размеры'),
        ),
    ]
