# Generated by Django 5.1.4 on 2025-03-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_review_obsluga_rating_review_quality_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='quality_rating',
            new_name='kachestvo_rating',
        ),
    ]
