# Generated by Django 5.1.4 on 2025-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_sizetable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politica_firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Политика конфиденциальности')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Uslovie_firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Условие сотрудничества')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
