# Generated by Django 5.1.4 on 2025-02-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_image_alter_product_article_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена старая'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='zacup_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена закупки'),
        ),
    ]
