# Generated by Django 5.1.4 on 2025-02-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_politica_firm_uslovie_firm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politica_firm',
            options={'verbose_name': 'Политика конфиденциальности', 'verbose_name_plural': 'Политика конфиденциальности'},
        ),
        migrations.AlterModelOptions(
            name='uslovie_firm',
            options={'verbose_name': 'Условие сотрудничества', 'verbose_name_plural': 'Условия сотрудничества'},
        ),
    ]
