# Generated by Django 5.1.4 on 2025-03-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_quality_rating_review_kachestvo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='kachestvo_rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='obsluga_rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='sroki_rating',
            field=models.PositiveIntegerField(),
        ),
    ]
