# Generated by Django 5.1.4 on 2025-02-09 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_product_old_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
