# Generated by Django 5.1.4 on 2025-02-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_politica_firm_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSliderHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_home/%Y/%m/%d', verbose_name='Изображение')),
            ],
        ),
    ]
