# Generated by Django 5.1.4 on 2025-02-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
