# Generated by Django 5.1.4 on 2025-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_deliveryinfo_alter_imagesliderhome_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryinfo',
            options={'verbose_name': 'Информацию по доставке', 'verbose_name_plural': 'Информация по доставке'},
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product'], name='home_produc_product_c7479f_idx'),
        ),
    ]
