# Generated by Django 5.1.4 on 2025-03-02 23:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_deliveryinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание новости'),
        ),
        migrations.AlterField(
            model_name='politica_firm',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='uslovie_firm',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
