# Generated by Django 5.1.4 on 2025-03-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_review_kachestvo_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='kachestvo_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='obsluga_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sroki_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.SmallIntegerField(default=0, verbose_name='Значение'),
        ),
    ]
