# Generated by Django 5.1.4 on 2025-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_review_kachestvo_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='kachestvo_rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Качество товара'),
        ),
        migrations.AlterField(
            model_name='review',
            name='obsluga_rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Качество обслуживания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sroki_rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Соблюдение сроков'),
        ),
    ]
