# Generated by Django 5.1.4 on 2025-03-10 09:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_review_kachestvo_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
