# Generated by Django 5.1.4 on 2025-03-10 09:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Отзыв'),
        ),
    ]
