# Generated by Django 5.1.4 on 2025-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_home/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
