# Generated by Django 5.1.4 on 2025-03-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_review_image_reviewimage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['size'], name='home_produc_size_id_bcc1b2_idx'),
        ),
    ]
