# Generated by Django 5.1.4 on 2025-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_productprice_home_produc_size_id_bcc1b2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Описание'),
        ),
    ]
